settings:
  username: "WilliamDavidHarrison"
  commit_msg: "Update Recent Activity"
  max_lines: 10
  readme_file: "README.md"
  disabled_events:
    - "push"
    - "wiki"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+0:00"
    text: "###### Last Updated: {DATE}"
    format: "dS mmmm, yyyy HH:MMtt Z"
  commit_name: "WDH-Bot"
  commit_email: "bot@williamharrison.dev"
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO}"
  pr_closed: "âŒ Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸ†• Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "âœ… Approved {ID} in {REPO}"
  changes_requested: "ğŸ”´ Requested changes in {ID} in {REPO}"
  new_release: "âœŒï¸ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"
