settings:
  username: "WilliamDavidHarrison"
  commit_msg: "Update Recent Activity"
  max_lines: 10
  line_prefix: ""
  readme_file: "README.md"
  disabled_events:
    - "push"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+0:00"
    text: "###### Last Updated: {DATE}"
    format: "dS mmmm, yyyy @ HH:MMtt Z"
  commit_name: "WDH-Bot"
  commit_email: "bot@williamharrison.dev"
messages:
  comments: "![comments](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Comment.svg) {ID} ({REPO})"
  issue_opened: "![issue_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueOpened.svg) {ID} ({REPO})"
  issue_closed: "![issue_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueClosed.svg) {ID} ({REPO})"
  pr_opened: "![pr_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestOpened.svg) {ID} ({REPO})"
  pr_closed: "![pr_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestClosed.svg) {ID} ({REPO})"
  pr_merged: "![pr_merged](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestMerged.svg) {ID} ({REPO})"
  create_repo: "![create_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Repository.svg) {REPO}"
  fork_repo: "![fork_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ForkedRepository.svg) {FORK} ({REPO})"
  wiki_create: "![wiki_create](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Wiki.svg) {WIKI} ({REPO})"
  added_member: "![added_member](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/People.svg) {REPO}"
  changes_approved: "![changes_approved](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ApprovedChanges.svg) {ID} ({REPO})"
  changes_requested: "![changes_requested](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/RequestedChanges.svg) {ID} ({REPO})"
  new_release: "![new_release](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Release.svg) {ID} ({REPO})"
  new_star: "![new_star](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/StarredRepositoryYellow.svg) {REPO}"
